name: Call a reusable workflow and use its outputs

on:
  push:
  workflow_dispatch:

jobs:
 job1:
  uses: 777abhi/playwright-typescript-basics/.github/workflows/workflowA.yml@chore-point-to-main-wf-reusable
 job2:
  runs-on: ubuntu-latest
  needs: job1
  steps:
    - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
 job3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Run JavaScript File and Set Output Environment Variable
        id: random_word
        run: |
          randomWord=$(node random-word.js)
          echo "RANDOM_WORD=${randomWord}" >> $GITHUB_ENV

      - name: Display RANDOM_WORD
        run: |
          echo "RANDOM_WORD=${{ env.RANDOM_WORD }}"